// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrBjmLxb2f1pbJPaUIOSsbYJGWJiSdikw',
    appId: '1:627822257528:ios:e3aab1a055d6553844548d',
    messagingSenderId: '627822257528',
    projectId: 'hopkins-summer-reading',
    storageBucket: 'hopkins-summer-reading.firebasestorage.app',
    androidClientId: '627822257528-5rl723c740l41dto4bp3vl34dgds84o6.apps.googleusercontent.com',
    iosClientId: '627822257528-2s713vegpk2aqsdnngusr374r6cra1nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNTPmju8wWMiqiync5IX8p3ra3jOPbtFs',
    appId: '1:627822257528:web:0768cb0a54c6512b44548d',
    messagingSenderId: '627822257528',
    projectId: 'hopkins-summer-reading',
    authDomain: 'hopkins-summer-reading.firebaseapp.com',
    storageBucket: 'hopkins-summer-reading.firebasestorage.app',
    measurementId: 'G-FRL2S3SCGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDicOAy32YbOhNkwW5y8knsB9LHpXY0z-g',
    appId: '1:627822257528:android:13439ee3fad6b30d44548d',
    messagingSenderId: '627822257528',
    projectId: 'hopkins-summer-reading',
    storageBucket: 'hopkins-summer-reading.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNTPmju8wWMiqiync5IX8p3ra3jOPbtFs',
    appId: '1:627822257528:web:0768cb0a54c6512b44548d',
    messagingSenderId: '627822257528',
    projectId: 'hopkins-summer-reading',
    authDomain: 'hopkins-summer-reading.firebaseapp.com',
    storageBucket: 'hopkins-summer-reading.firebasestorage.app',
    measurementId: 'G-FRL2S3SCGZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrBjmLxb2f1pbJPaUIOSsbYJGWJiSdikw',
    appId: '1:627822257528:ios:e3aab1a055d6553844548d',
    messagingSenderId: '627822257528',
    projectId: 'hopkins-summer-reading',
    storageBucket: 'hopkins-summer-reading.firebasestorage.app',
    androidClientId: '627822257528-5rl723c740l41dto4bp3vl34dgds84o6.apps.googleusercontent.com',
    iosClientId: '627822257528-2s713vegpk2aqsdnngusr374r6cra1nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapps',
  );

}