// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: String.fromEnvironment(
      'MACOS_FIREBASE_API_KEY',
      defaultValue: 'AIzaSyBrBjmLxb2f1pbJPaUIOSsbYJGWJiSdikw',
    ),
    appId: String.fromEnvironment(
      'MACOS_FIREBASE_APP_ID',
      defaultValue: '1:627822257528:ios:4a11e0e514f4b12244548d',
    ),
    messagingSenderId: String.fromEnvironment(
      'FIREBASE_MESSAGING_SENDER_ID',
      defaultValue: '627822257528',
    ),
    projectId: String.fromEnvironment(
      'FIREBASE_PROJECT_ID',
      defaultValue: 'hopkins-summer-reading',
    ),
    storageBucket: String.fromEnvironment(
      'FIREBASE_STORAGE_BUCKET',
      defaultValue: 'hopkins-summer-reading.firebasestorage.app',
    ),
    iosBundleId: String.fromEnvironment(
      'IOS_BUNDLE_ID',
      defaultValue: 'com.example.libraryApp',
    ),
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: String.fromEnvironment(
      'WINDOWS_FIREBASE_API_KEY',
      defaultValue: 'AIzaSyCNTPmju8wWMiqiync5IX8p3ra3jOPbtFs',
    ),
    appId: String.fromEnvironment(
      'WINDOWS_FIREBASE_APP_ID',
      defaultValue: '1:627822257528:web:0768cb0a54c6512b44548d',
    ),
    messagingSenderId: String.fromEnvironment(
      'FIREBASE_MESSAGING_SENDER_ID',
      defaultValue: '627822257528',
    ),
    projectId: String.fromEnvironment(
      'FIREBASE_PROJECT_ID',
      defaultValue: 'hopkins-summer-reading',
    ),
    authDomain: String.fromEnvironment(
      'FIREBASE_AUTH_DOMAIN',
      defaultValue: 'hopkins-summer-reading.firebaseapp.com',
    ),
    storageBucket: String.fromEnvironment(
      'FIREBASE_STORAGE_BUCKET',
      defaultValue: 'hopkins-summer-reading.firebasestorage.app',
    ),
    measurementId: String.fromEnvironment(
      'FIREBASE_MEASUREMENT_ID',
      defaultValue: 'G-FRL2S3SCGZ',
    ),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: String.fromEnvironment(
      'ANDROID_FIREBASE_API_KEY',
      defaultValue: 'AIzaSyDicOAy32YbOhNkwW5y8knsB9LHpXY0z-g',
    ),
    appId: String.fromEnvironment(
      'ANDROID_FIREBASE_APP_ID',
      defaultValue: '1:627822257528:android:13439ee3fad6b30d44548d',
    ),
    messagingSenderId: String.fromEnvironment(
      'FIREBASE_MESSAGING_SENDER_ID',
      defaultValue: '627822257528',
    ),
    projectId: String.fromEnvironment(
      'FIREBASE_PROJECT_ID',
      defaultValue: 'hopkins-summer-reading',
    ),
    storageBucket: String.fromEnvironment(
      'FIREBASE_STORAGE_BUCKET',
      defaultValue: 'hopkins-summer-reading.firebasestorage.app',
    ),
  );
}
