// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrBjmLxb2f1pbJPaUIOSsbYJGWJiSdikw',
    appId: '1:627822257528:ios:4a11e0e514f4b12244548d',
    messagingSenderId: '627822257528',
    projectId: 'hopkins-summer-reading',
    storageBucket: 'hopkins-summer-reading.firebasestorage.app',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNTPmju8wWMiqiync5IX8p3ra3jOPbtFs',
    appId: '1:627822257528:web:0768cb0a54c6512b44548d',
    messagingSenderId: '627822257528',
    projectId: 'hopkins-summer-reading',
    authDomain: 'hopkins-summer-reading.firebaseapp.com',
    storageBucket: 'hopkins-summer-reading.firebasestorage.app',
    measurementId: 'G-FRL2S3SCGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDicOAy32YbOhNkwW5y8knsB9LHpXY0z-g',
    appId: '1:627822257528:android:13439ee3fad6b30d44548d',
    messagingSenderId: '627822257528',
    projectId: 'hopkins-summer-reading',
    storageBucket: 'hopkins-summer-reading.firebasestorage.app',
  );

}